name: ffmpeg_gnu
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ffmpeg=4.2
  - jupyter
  - pandas=1.0.2
  - matplotlib=3.1.3
  - gnuradio
  - pip
  - pip:
      - ffmpeg_python
      - pybombs
      #- "--editable=git+https://github.com/pythonforfacebook/facebook-sdk.git@8c0d34291aaafec00e02eaa71cc2a242790a0fcc#egg=facebook_sdk-master"